PV2-3163 add DASProviderEvents database project
SkillsFundingAgency/das-providerevents pull request #138
Opened 2023-11-08 13:16 UTC by David-B-Read

2023-11-08 13:37 UTC, LiamWright submitted a review, later dismissed

2023-12-22 11:39 UTC, abroodie requested changes
Looks like there are some missing indexes

2023-12-22 11:39 UTC, abroodie commented on src/api/SFA.DAS.Provider.Events.Database/DataLock/Tables/DataLockEventCommitmentVersions.sql
> +﻿CREATE TABLE [DataLock].[DataLockEventCommitmentVersions](
missing indexes
CREATE NONCLUSTERED INDEX [IX_DataLockEventCommitmentVersions_DataLockEventId] ON [DataLock].[DataLockEventCommitmentVersions]
(
    [DataLockEventId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DataLockEventCommitmentVersions_DataLockId] ON [DataLock].[DataLockEventCommitmentVersions]
(
    [DataLockEventId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

2023-12-22 11:39 UTC, abroodie commented on src/api/SFA.DAS.Provider.Events.Database/DataLock/Tables/DataLockEventPeriods.sql
> +﻿CREATE TABLE [DataLock].[DataLockEventPeriods](
Missing index 
CREATE NONCLUSTERED INDEX [IX_DataLockEventPeriods_DataLockId] ON [DataLock].[DataLockEventPeriods]
(
    [DataLockEventId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

2023-12-22 11:39 UTC, abroodie commented on src/api/SFA.DAS.Provider.Events.Database/DataLock/Tables/DataLockEvents.sql
> +﻿CREATE TABLE [DataLock].[DataLockEvents](
missing index 
CREATE NONCLUSTERED INDEX [IX_DataLockEvents_DataLockId] ON [DataLock].[DataLockEvents]
(
    [DataLockEventId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

2023-12-22 11:39 UTC, abroodie commented on src/api/SFA.DAS.Provider.Events.Database/Submissions/Tables/LastSeenVersion.sql
> +﻿CREATE TABLE [Submissions].[LastSeenVersion](
missing index 
CREATE NONCLUSTERED INDEX [IX_LastSeenVersion_UKPRN] ON [Submissions].[LastSeenVersion]
(
    [UKPRN] ASC,
    [LearnRefNumber] ASC,
    [PriceEpisodeIdentifier] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

2024-01-26 15:29 UTC, abroodie approved these changes, later dismissed

2025-11-04 16:01 UTC, LiamWright approved these changes

2026-02-26 15:23 UTC, syed-wali approved these changes

2026-02-26 15:26 UTC, merged